### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by sdwilko** [gandf/android_device_nubia_nx589j#1]
Have you managed to compile from this device tree? If so, how? Also, can I share with the Mokee Open Source Project for ROM development?

**Comment by gandf** [comment]
One version compile with kernel prebuilt only with "make recovery".
But zip is not done and I don't have test this build.
With kernel, I have several issue due to old kernel source. Some "include directory" are deprecated and broke compilation.
Now, I work on kernel to merge with another kernel that work to compile.
Don't take my work now. It's to my interne build because I use old PC and don't want to lost my work if it crash.
I add/update readme when it's work.

**Comment by gandf** [comment]
If you want to take a base, uses commit e80878862e6126707de08be315ddaea20421408a. Not the last commit.

**Comment by sdwilko** [comment]
OK, thanks for the pointers 👍 

Will give it a crack. I have the same device so will try some things on my end too. Will create a pull request if I get anywhere :)

Thanks
